// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package internal

import (
	"context"
)

// iteratorForCreateImages implements pgx.CopyFromSource.
type iteratorForCreateImages struct {
	rows                 []CreateImagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateImages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateImages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Url,
		r.rows[0].AltText,
		r.rows[0].Embedding,
	}, nil
}

func (r iteratorForCreateImages) Err() error {
	return nil
}

func (q *Queries) CreateImages(ctx context.Context, arg []CreateImagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"images"}, []string{"url", "alt_text", "embedding"}, &iteratorForCreateImages{rows: arg})
}

// iteratorForCreatePostings implements pgx.CopyFromSource.
type iteratorForCreatePostings struct {
	rows                 []CreatePostingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePostings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePostings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Word,
		r.rows[0].PageID,
		r.rows[0].Tf,
	}, nil
}

func (r iteratorForCreatePostings) Err() error {
	return nil
}

func (q *Queries) CreatePostings(ctx context.Context, arg []CreatePostingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"postings"}, []string{"word", "page_id", "tf"}, &iteratorForCreatePostings{rows: arg})
}

// iteratorForInsertLinks implements pgx.CopyFromSource.
type iteratorForInsertLinks struct {
	rows                 []InsertLinksParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLinks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLinks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FromPageID,
		r.rows[0].ToPageID,
	}, nil
}

func (r iteratorForInsertLinks) Err() error {
	return nil
}

func (q *Queries) InsertLinks(ctx context.Context, arg []InsertLinksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"links"}, []string{"from_page_id", "to_page_id"}, &iteratorForInsertLinks{rows: arg})
}
