// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package internal

import (
	"context"
)

// iteratorForCreateBlankPages implements pgx.CopyFromSource.
type iteratorForCreateBlankPages struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBlankPages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBlankPages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateBlankPages) Err() error {
	return nil
}

// this one is made so when indexing a page, we first create blank pages to the forward links
// to update the links, then later we update these pages
func (q *Queries) CreateBlankPages(ctx context.Context, url []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"pages"}, []string{"url"}, &iteratorForCreateBlankPages{rows: url})
}

// iteratorForInsertLinks implements pgx.CopyFromSource.
type iteratorForInsertLinks struct {
	rows                 []InsertLinksParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLinks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLinks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FromPageID,
		r.rows[0].ToPageID,
	}, nil
}

func (r iteratorForInsertLinks) Err() error {
	return nil
}

func (q *Queries) InsertLinks(ctx context.Context, arg []InsertLinksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"links"}, []string{"from_page_id", "to_page_id"}, &iteratorForInsertLinks{rows: arg})
}
