// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package internal

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const createImages = `-- name: CreateImages :exec
INSERT INTO images(url,alt_text,embedding,url_hash) 
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::Vector(384)[]),unnest($4::text[])
ON CONFLICT (url_hash) DO NOTHING
`

type CreateImagesParams struct {
	Urls       []string
	Alttexts   []string
	Embeddings []pgvector.Vector
	Hashes     []string
}

func (q *Queries) CreateImages(ctx context.Context, arg CreateImagesParams) error {
	_, err := q.db.Exec(ctx, createImages,
		arg.Urls,
		arg.Alttexts,
		arg.Embeddings,
		arg.Hashes,
	)
	return err
}
