// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package internal

import (
	"context"
)

const getBackLinkIds = `-- name: GetBackLinkIds :many
SELECT from_page_id FROM links 
WHERE (to_page_id = $1)
`

func (q *Queries) GetBackLinkIds(ctx context.Context, toPageID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getBackLinkIds, toPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var from_page_id int32
		if err := rows.Scan(&from_page_id); err != nil {
			return nil, err
		}
		items = append(items, from_page_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getForwardLinkIds = `-- name: GetForwardLinkIds :many
SELECT to_page_id FROM links 
WHERE (from_page_id = $1)
`

func (q *Queries) GetForwardLinkIds(ctx context.Context, fromPageID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getForwardLinkIds, fromPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var to_page_id int32
		if err := rows.Scan(&to_page_id); err != nil {
			return nil, err
		}
		items = append(items, to_page_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertLinksParams struct {
	FromPageID int32
	ToPageID   int32
}
