// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package internal

import (
	"context"
)

const updateDocCountAndAvgDocLength = `-- name: UpdateDocCountAndAvgDocLength :one
INSERT INTO metadata (id, total_documents, avg_doc_length)
VALUES (true, 1, $1)
ON CONFLICT (id) DO UPDATE
SET
    total_documents = total_documents + 1,
    avg_doc_length = (
        avg_doc_length * total_documents + $1
    ) / (total_documents + 1)
RETURNING id, total_documents, avg_doc_length, last_idf_update
`

func (q *Queries) UpdateDocCountAndAvgDocLength(ctx context.Context, avgDocLength float32) (Metadata, error) {
	row := q.db.QueryRow(ctx, updateDocCountAndAvgDocLength, avgDocLength)
	var i Metadata
	err := row.Scan(
		&i.ID,
		&i.TotalDocuments,
		&i.AvgDocLength,
		&i.LastIdfUpdate,
	)
	return i, err
}
