// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package internal

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Image struct {
	ID        int32
	AltText   string
	Url       string
	Embedding pgvector.Vector
}

type Link struct {
	FromPageID int32
	ToPageID   int32
}

type Page struct {
	ID        int32
	Url       string
	Title     pgtype.Text
	Heading   pgtype.Text
	Embedding pgvector.Vector
	CrawledAt pgtype.Timestamp
}

type Posting struct {
	ID     int32
	Word   string
	PageID int32
	Tf     float32
	TfIdf  float32
}
