// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package internal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createBlankPages = `-- name: CreateBlankPages :many
INSERT INTO pages (url)
SELECT unnest($1::text[])
RETURNING id, url, title, heading, embedding, doc_length, crawled_at
`

// this one is made so when indexing a page, we first create blank pages to the forward links
// to update the links, then later we update these pages
func (q *Queries) CreateBlankPages(ctx context.Context, dollar_1 []string) ([]Page, error) {
	rows, err := q.db.Query(ctx, createBlankPages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Heading,
			&i.Embedding,
			&i.DocLength,
			&i.CrawledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages( url,heading,title,embedding) 
VALUES($1,$2,$3,$4) 
ON CONFLICT (url) DO 
UPDATE SET heading = $2, title = $3 , embedding = $4
RETURNING id, url, title, heading, embedding, doc_length, crawled_at
`

type CreatePageParams struct {
	Url       string
	Heading   pgtype.Text
	Title     pgtype.Text
	Embedding pgvector.Vector
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Url,
		arg.Heading,
		arg.Title,
		arg.Embedding,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Heading,
		&i.Embedding,
		&i.DocLength,
		&i.CrawledAt,
	)
	return i, err
}

const getAllPages = `-- name: GetAllPages :many
SELECT id, url, title, heading, embedding, doc_length, crawled_at FROM pages
`

func (q *Queries) GetAllPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, getAllPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Heading,
			&i.Embedding,
			&i.DocLength,
			&i.CrawledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageById = `-- name: GetPageById :one
SELECT id, url, title, heading, embedding, doc_length, crawled_at 
FROM pages 
WHERE (id = $1)
`

func (q *Queries) GetPageById(ctx context.Context, id int32) (Page, error) {
	row := q.db.QueryRow(ctx, getPageById, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Heading,
		&i.Embedding,
		&i.DocLength,
		&i.CrawledAt,
	)
	return i, err
}

const getPageByUrl = `-- name: GetPageByUrl :one
SELECT id, url, title, heading, embedding, doc_length, crawled_at 
FROM pages 
WHERE (url = $1)
`

func (q *Queries) GetPageByUrl(ctx context.Context, url string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByUrl, url)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Heading,
		&i.Embedding,
		&i.DocLength,
		&i.CrawledAt,
	)
	return i, err
}
