// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postings.sql

package internal

import (
	"context"
)

const createPosting = `-- name: CreatePosting :one
INSERT INTO postings(word,page_id,tf,tf_idf) VALUES($1,$2,$3,$4) 
RETURNING id, word, page_id, tf, tf_idf
`

type CreatePostingParams struct {
	Word   string
	PageID int32
	Tf     float32
	TfIdf  float32
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, createPosting,
		arg.Word,
		arg.PageID,
		arg.Tf,
		arg.TfIdf,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.PageID,
		&i.Tf,
		&i.TfIdf,
	)
	return i, err
}

const getAllPostings = `-- name: GetAllPostings :many
SELECT id, word, page_id, tf, tf_idf FROM postings
`

func (q *Queries) GetAllPostings(ctx context.Context) ([]Posting, error) {
	rows, err := q.db.Query(ctx, getAllPostings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.PageID,
			&i.Tf,
			&i.TfIdf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostingById = `-- name: GetPostingById :one
SELECT id, word, page_id, tf, tf_idf FROM postings 
WHERE (id = $1)
`

func (q *Queries) GetPostingById(ctx context.Context, id int32) (Posting, error) {
	row := q.db.QueryRow(ctx, getPostingById, id)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.PageID,
		&i.Tf,
		&i.TfIdf,
	)
	return i, err
}

const updateTfIdf = `-- name: UpdateTfIdf :one
UPDATE postings 
SET tf_idf = $2
WHERE (id = $1)
RETURNING id, word, page_id, tf, tf_idf
`

type UpdateTfIdfParams struct {
	ID    int32
	TfIdf float32
}

func (q *Queries) UpdateTfIdf(ctx context.Context, arg UpdateTfIdfParams) (Posting, error) {
	row := q.db.QueryRow(ctx, updateTfIdf, arg.ID, arg.TfIdf)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.PageID,
		&i.Tf,
		&i.TfIdf,
	)
	return i, err
}
