// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terms.sql

package internal

import (
	"context"
)

const createTerms = `-- name: CreateTerms :many
INSERT INTO terms (term) 
SELECT unnest($1::text[])
ON CONFLICT (term) DO 
UPDATE SET df = terms.df + 1
RETURNING term, df, idf
`

func (q *Queries) CreateTerms(ctx context.Context, dollar_1 []string) ([]Term, error) {
	rows, err := q.db.Query(ctx, createTerms, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Term
	for rows.Next() {
		var i Term
		if err := rows.Scan(&i.Term, &i.Df, &i.Idf); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
