// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocab.sql

package internal

import (
	"context"
)

const createVocabs = `-- name: CreateVocabs :many
INSERT INTO vocab (word, stem)
SELECT unnest($1::text[]), unnest($2::text[])
ON CONFLICT (word) DO NOTHING
RETURNING word, stem
`

type CreateVocabsParams struct {
	Column1 []string
	Column2 []string
}

func (q *Queries) CreateVocabs(ctx context.Context, arg CreateVocabsParams) ([]Vocab, error) {
	rows, err := q.db.Query(ctx, createVocabs, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vocab
	for rows.Next() {
		var i Vocab
		if err := rows.Scan(&i.Word, &i.Stem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
